export const beanPuns = [
    "Bean there, done that.",
    "Don't spill the beans — unless it's coffee.",
    "I'm full of beans today!",
    "Not worth a hill of beans.",
    "Bean me up, Scotty!",
    "That joke was bean-tastic.",
    "We're in a bit of a beanstalk situation.",
    "Stop bean so dramatic.",
    "Bean counting is my favorite hobby.",
    "Give peas a chance — but pass the beans.",
    "Bean around the world in eighty meals.",
    "That's the best thing since sliced beans.",
    "I have bean thinking about you.",
    "Bean careful what you wish for.",
    "This is unbe-leaf-able — I mean, unbeAN-able.",
    "You're a has-bean? Never!",
    "Morning meetings: pour-over and beans.",
    "Bean on a mission.",
    "You bean saying what I bean hearing?",
    "A bean a day keeps the grumpies away.",
    "You can't handle the bean-th!",
    "Bean there for you through thick and thin.",
    "Bean team, dream team.",
    "That idea really beans well.",
    "I can't espresso how much I love beans.",
    "Bean me a favor and pass the salt.",
    "That pun was legume-inous.",
    "Bean thinking outside the pod.",
    "You're the bean to my toast.",
    "Keep your friends close and your beans closer.",
    "Bean jealous? Don't be.",
    "No beans, no glory.",
    "Bean working on my stand-up routine.",
    "This party is bean-booming.",
    "Bean in love with these flavors.",
    "Let sleeping beans lie.",
    "Bean a while since we last met.",
    "Bean-ding the rules a little.",
    "Bean on the bright side.",
    "Bean hunting for a snack.",
    "You're a real bean-count of joy.",
    "Let's get to the bean-essence of it.",
    "Bean prepared for anything.",
    "Bean there for a good time, not a long time.",
    "Bean-sational performance!",
    "Don't be a has-bean — be a will-bean.",
    "Bean carefully, this one's hot.",
];
